framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict

symfonycasts_tailwind:
    binary_version: 'v3.4.17'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
