doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '9.6'
        charset: utf8

        url: '%env(resolve:DATABASE_URL)%'

        types:
            array_collection: 'ParkManager\Infrastructure\Doctrine\Type\ArrayCollectionType'
            park_manager_user_id: 'ParkManager\Infrastructure\Doctrine\Type\UserIdType'
            park_manager_organization_id: 'ParkManager\Infrastructure\Doctrine\Type\OrganizationIdType'
            park_manager_owner_id: 'ParkManager\Infrastructure\Doctrine\Type\OwnerIdType'
            #park_manager_domain_id: 'ParkManager\Infrastructure\Doctrine\Type\DomainIdType' # Don't initiate this
            cidr: 'ParkManager\Infrastructure\Doctrine\Type\CidrType'
            carbon_immutable: 'Carbon\Doctrine\CarbonImmutableType'

            # Webhosting
            byte_size: 'ParkManager\Infrastructure\Doctrine\Type\ByteSizeType'
            park_manager_webhosting_space_id: 'ParkManager\Infrastructure\Doctrine\Type\WebhostingSpaceIdType'
            park_manager_webhosting_plan_id: 'ParkManager\Infrastructure\Doctrine\Type\WebhostingPlanIdType'
            park_manager_domain_name_id: 'ParkManager\Infrastructure\Doctrine\Type\DomainNameIdType'
            park_manager_sub_domain_id: 'ParkManager\Infrastructure\Doctrine\Type\SubDomainNameIdType'
            park_manager_webhosting_mailbox_id: 'ParkManager\Infrastructure\Doctrine\Type\MailboxIdType'
            park_manager_webhosting_mail_forward_id: 'ParkManager\Infrastructure\Doctrine\Type\MailForwardIdType'
            park_manager_ftp_user_id: 'ParkManager\Infrastructure\Doctrine\Type\Webhosting\FtpUserIdType'
            park_manager_ftp_access_rule_id: 'ParkManager\Infrastructure\Doctrine\Type\Webhosting\FtpAccessRuleIdType'
            park_manager_scheduled_task_id: 'ParkManager\Infrastructure\Doctrine\Type\Webhosting\TaskIdType'
            park_manager_scheduled_task_condition: 'ParkManager\Infrastructure\Doctrine\Type\Webhosting\ScheduledTaskConditionType'

        mapping_types:
            cidr: string

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'ParkManager\Domain'
                alias: ParkManager
            SecurityMapping:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/SecurityMapping'
                prefix: 'Rollerworks\Component\SplitToken'
