rollerworks_pdb:
    cache_pool: 'rollerworks.cache.public_prefix_db'
    manager: static # either: 'http' (default), 'static' (requires manual updates) or 'mock'

framework:
    cache:
        pools:
            # This name can be changed by setting `rollerworks_pdb.cache_pool` (**Don't reuse an existing cache pool!**)
            rollerworks.cache.public_prefix_db:
                adapter: cache.adapter.doctrine_dbal
                default_lifetime: 604800 # one week, the cache should be automatically refreshed

