FROM jakzal/phpqa:alpine

COPY qa/tools.json $TOOLBOX_TARGET_DIR/extra-tools.json

RUN php $TOOLBOX_TARGET_DIR/toolbox install --tools $TOOLBOX_TARGET_DIR/extra-tools.json \
  && rm -rf ~/.composer/cache

ENV TOOLBOX_JSON="phar://$TOOLBOX_TARGET_DIR/toolbox/resources/pre-installation.json,phar://$TOOLBOX_TARGET_DIR/toolbox/resources/tools.json,$TOOLBOX_TARGET_DIR/extra-tools.json"
