
parameters:
    locale: en
    # This parameter defines the codes of the locales (languages) enabled in the application, and there preferred order.
    accepted_locales: [en, nl] # ar, en, fr, de, es, cs, nl, ru, uk, ro, pt_BR, pl, it, ja, id, ca, sl, hr, zh_CN, bg, tr, lt, bs, sr_Cyrl, sr_Latn
